name: 🚀 Deploy TEST Stage backup-wp-plugin

on:
  push:
    branches:  
      - "feature/**"

jobs:
  web-deploy:
    name: 🎉 Deploy at https://spielwiese.erfindergeist.org/
    runs-on: ubuntu-latest

    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 🐘 Setup PHP & Composer
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        tools: composer
        coverage: none

    - name: 📦 Install runtime dependencies
      run: composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader

    - name: 📂 Sync files
      uses: ./.github/actions/ftp-deploy
      with:
        username: ${{ secrets.FTP_USERNAME_TEST }}
        password: ${{ secrets.FTP_PASSWORD_TEST }}
        state-name: .ftp-deploy-test-stage-backup-wp-plugin-state.json
